server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;
    absolute_redirect off;
    ssi on;

    location /partials/ {
        internal;
    }

    location /files/ {
        alias /data/uploads/;
    }

    location ~ ^/w/[^/]+/ask/?$ {
        try_files /w/ask/index.html =404;
    }

    location ~ ^/w/[^/]+/?$ {
        try_files /w/ask/index.html =404;
    }

    location ~ ^/w/[^/]+/feed/files/?$ {
        try_files /w/feed/files/index.html =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location /api/ {
        proxy_pass http://backend:8000/;
    }
}
